[package]
name = "cubox"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
getopts = "0.2"
dirs = "4.0.0"
chrono = {version = "0.4", features = ["serde"] }
colored = "2.0.0"